"A list of settings, ones followed by a '#!', should not be altered."
from os.path import sep

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)#!

CAMERA_WIDTH = 800
CAMERA_HEIGHT = 600
CAMERA_SIZE = (CAMERA_WIDTH, CAMERA_HEIGHT)#!

CAMERA_START_X = 0
CAMERA_START_Y = 0
CAMERA_START = (CAMERA_START_X, CAMERA_START_Y)#!

DISPLAY_WIDTH = 800
DISPLAY_HEIGHT = 600
DISPLAY_SIZE = (DISPLAY_WIDTH, DISPLAY_HEIGHT)#!

PLAYER_START_X = 0
PLAYER_START_Y = 0
PLAYER_START = (PLAYER_START_X, PLAYER_START_Y)#!

PLAYER_WIDTH = 64
PLAYER_HEIGHT = 64
PLAYER_SIZE = (PLAYER_WIDTH, PLAYER_HEIGHT)#!

TILE_WIDTH = 64
TILE_HEIGHT = 64
TILE_SIZE = (TILE_WIDTH, TILE_HEIGHT)#!

START_MAP = "maps" + sep + "test_map.json"

VOID_COLOR = (0, 0, 0)
GAME_TITLE = "Science is Flammable!"

FRAME_MOVE = 8
